[versions]
agp = "8.5.2"
kotlin = "2.0.0"
hilt = "2.52"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt         = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt-android        = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
